//
//  IntroPageRouter.swift
//  fuelhunter
//
//  Created by Guntis on 16/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol IntroPageRoutingLogic {
  	//func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol IntroPageDataPassing {
  	var dataStore: IntroPageDataStore? { get }
}

public class IntroPageRouter: NSObject, IntroPageRoutingLogic, IntroPageDataPassing {
  	weak var viewController: IntroPageViewController?
  	var dataStore: IntroPageDataStore?
}
