//
//  IntroPageModels.swift
//  fuelhunter
//
//  Created by Guntis on 16/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum IntroPage {
  	// MARK: Use cases
	enum Something {
		struct Request {
		}
		struct Response {
		}
		struct ViewModel {
		}
  	}
}
