//
//  IntroPageViewController.swift
//  fuelhunter
//
//  Created by Guntis on 16/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol IntroPageDisplayLogic: class {
  	func displaySomething(viewModel: IntroPage.Something.ViewModel)
}

class IntroPageViewController: UIViewController, IntroPageDisplayLogic, IntroPageLayoutViewLogic {

  	var interactor: IntroPageBusinessLogic?
  	var router: (NSObjectProtocol & IntroPageRoutingLogic & IntroPageDataPassing)?

	// MARK: Object lifecycle

  	override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    	super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    	setup()
  	}

  	required init?(coder aDecoder: NSCoder) {
    	super.init(coder: aDecoder)
    	setup()
  	}

  	// MARK: View lifecycle

  	override func viewDidLoad() {
    	super.viewDidLoad()
    	self.view.backgroundColor = .white
    	setUpView()
    	doSomething()
  	}

	// MARK: Set up

	private func setup() {
		let viewController = self
		let interactor = IntroPageInteractor()
		let presenter = IntroPagePresenter()
		let router = IntroPageRouter()
		viewController.interactor = interactor
		viewController.router = router
		interactor.presenter = presenter
		presenter.viewController = viewController
		router.viewController = viewController
		router.dataStore = interactor
  	}

	func setUpView() {
		let view = IntroPageLayoutView(frame: CGRect(x: 0, y: 0, width: self.view.frame.width, height: 100))
		self.view.addSubview(view)
		view.topAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.topAnchor).isActive = true
		view.widthAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.widthAnchor).isActive = true
		view.bottomAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.bottomAnchor).isActive = true
		view.controller = self
	}

  	// MARK: Functions

	func nextButtonWasPressed() {
		ScenesManager.shared.advanceAppSceneState()
	}

  	func doSomething() {
    	let request = IntroPage.Something.Request()
    	interactor?.doSomething(request: request)
  	}

  	func displaySomething(viewModel: IntroPage.Something.ViewModel) {
    	//nameTextField.text = viewModel.name
  	}
}
