//
//  IntroPageInteractor.swift
//  fuelhunter
//
//  Created by Guntis on 16/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol IntroPageBusinessLogic {
  	func doSomething(request: IntroPage.Something.Request)
}

protocol IntroPageDataStore {
  	//var name: String { get set }
}

public class IntroPageInteractor: IntroPageBusinessLogic, IntroPageDataStore {
  	var presenter: IntroPagePresentationLogic?
  	var worker: IntroPageWorker?
  	//var name: String = ""

  	// MARK: IntroPageBusinessLogic

  	func doSomething(request: IntroPage.Something.Request) {
    	worker = IntroPageWorker()
    	worker?.doSomeWork()
    	let response = IntroPage.Something.Response()
    	presenter?.presentSomething(response: response)
  	}
}
