//
//  NewAreaPageRouter.swift
//  fuelhunter
//
//  Created by Guntis on 10/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


@objc protocol NewAreaPageViewRoutingLogic {
	func routeToSetUp()
}

protocol NewAreaPagetDataPassing {
	var navigationController: UINavigationController? { get set }
}


class NewAreaPageRouter: NSObject, NewAreaPageViewRoutingLogic, NewAreaPagetDataPassing {
	weak var viewController: NewAreaPageViewController?
	var navigationController: UINavigationController?

	// MARK: LoadedCityExplainViewRoutingLogic

	func routeToSetUp() {
		let destinationVC = AreaSetUpPageViewController()
//		destinationVC.router?.previousViewController = self
  		destinationVC.providesPresentationContextTransitionStyle = true
		destinationVC.definesPresentationContext = true
		destinationVC.modalPresentationStyle=UIModalPresentationStyle.overCurrentContext
		self.navigationController!.present(destinationVC, animated: true) { }
	}
}
