//
//  MainViewsListPresenter.swift
//  fuelhunter
//
//  Created by Guntis on 03/06/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreData

protocol MainViewsListPresentationLogic {
	func presentData(response: MainViewsList.FetchAreas.Response)
}

class MainViewsListPresenter: MainViewsListPresentationLogic {
	weak var viewController: MainViewsListDisplayLogic?

	// MARK: MainViewsListPresentationLogic

	func presentData(response: MainViewsList.FetchAreas.Response) {

		var array: [MainViewsList.FetchAreas.ViewModel.DisplayedArea] = []

		for area in response.fetchedAreas {
			if area.isGPSArea {
				array.append(MainViewsList.FetchAreas.ViewModel.DisplayedArea(name: AppSettingsWorker.shared.getStoredLastGPSDetectedCityName(), type: .areaTypeGPS))
			} else {
				array.append(MainViewsList.FetchAreas.ViewModel.DisplayedArea(name: area.name!, type: .areaTypeAdded))
			}
		}

		let viewModel = MainViewsList.FetchAreas.ViewModel(displayedAreas: array)
    	viewController?.displayData(viewModel: viewModel)
	}
}
