//
//  MainViewsListModels.swift
//  fuelhunter
//
//  Created by Guntis on 03/06/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreData

enum MainViewsList {
	// MARK: Use cases

	enum FetchAreas {
		struct Request {
		}
		struct Response {
			var fetchedAreas: [AreasEntity]
		}
		struct ViewModel {
			struct DisplayedArea: Equatable {
				var name: String
				var type: AreaType
				
			}
			var displayedAreas: [DisplayedArea]
		}
	}
}
