//
//  MainViewsListWorker.swift
//  fuelhunter
//
//  Created by Guntis on 03/06/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreData
class MainViewsListWorker {

	func createGPSArea() -> AreasEntity {
		let gpsArea = AreasEntity.init(context: DataBaseManager.shared.mainManagedObjectContext())

		return gpsArea;
	}

}
