//
//  MainViewsListRouter.swift
//  fuelhunter
//
//  Created by Guntis on 03/06/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainViewsListRoutingLogic {
	func routeToSettings()
	func routeToAreasList()
}

protocol MainViewsListDataPassing {
	var dataStore: MainViewsListDataStore? { get }
}

class MainViewsListRouter: NSObject, MainViewsListRoutingLogic, MainViewsListDataPassing {
	weak var viewController: MainViewsListViewController?
	var dataStore: MainViewsListDataStore?
	
  	// MARK: MainViewsListRoutingLogic

	@objc func routeToSettings() {
		viewController?.navigationController?.delegate = nil
  		navigateTo(source: viewController!, destination: SettingsViewController())
  	}

	@objc func routeToAreasList() {
		viewController?.navigationController?.delegate = nil
  		navigateTo(source: viewController!, destination: AreasEditListViewController())
	}

  	// MARK: Functions

	private func navigateTo(source: MainViewsListViewController, destination: UIViewController) {
		source.navigationItem.backBarButtonItem = UIBarButtonItem(title: "", style: .plain, target: nil, action: nil)
		source.navigationController?.navigationBar.topItem?.backBarButtonItem = UIBarButtonItem(title: "", style: .plain, target: nil, action: nil)
		source.show(destination, sender: nil)
  	}
}
