//
//  PushNotifSetupPresenter.swift
//  fuelhunter
//
//  Created by Guntis on 10/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PushNotifSetupPresentationLogic {
  	func presentData(response: PushNotifSetup.SetUp.Response)
  	func returnBackToPreviousViewController()
}

class PushNotifSetupPresenter: PushNotifSetupPresentationLogic {
  	weak var viewController: PushNotifSetupDisplayLogic?
	weak var router: PushNotifSetupRouter?
  	// MARK: Do something

  	func presentData(response: PushNotifSetup.SetUp.Response) {
  	
  		var descriptionString = "Saņemt paziņojumus, kad degvielas cena samazinās par "
  		
  		if response.value == 1 {
  			descriptionString.append("\(response.convertedValue) centu.")
  		} else {
  			descriptionString.append("\(response.convertedValue) centiem.")
  		}
  		
  		let displayItem = PushNotifSetup.SetUp.ViewModel.DisplayedItem.init(description: descriptionString, value: response.value, minValue: response.minValue, maxValue: response.maxValue)
  		
    	let viewModel = PushNotifSetup.SetUp.ViewModel.init(displayedItem: displayItem)
    	viewController?.updateData(viewModel: viewModel)
  	}
  	
  	func returnBackToPreviousViewController() {
  		router?.dismissCurrentViewController()
  	}
}
