//
//  FuelTypeChooseListPresenter.swift
//  fuelhunter
//
//  Created by Guntis on 05/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FuelTypeChooseListPresentationLogic {
  	func displayListWithData(response: FuelTypeChooseList.FuelCells.Response)
}

class FuelTypeChooseListPresenter: FuelTypeChooseListPresentationLogic {
  	weak var viewController: FuelTypeChooseListDisplayLogic?

  	// MARK: Do something

	let array =  [
			FuelTypeChooseList.FuelCells.ViewModel.DisplayedFuelCellItem.init(title: "DD | Dīzeļdegviela", toggleStatus: true),
			FuelTypeChooseList.FuelCells.ViewModel.DisplayedFuelCellItem.init(title: "DD | Pro Dīzeļdegviela", toggleStatus: false),
			FuelTypeChooseList.FuelCells.ViewModel.DisplayedFuelCellItem.init(title: "95 | Benzīns", toggleStatus: false),
			FuelTypeChooseList.FuelCells.ViewModel.DisplayedFuelCellItem.init(title: "98 | Benzīns", toggleStatus: false),
			FuelTypeChooseList.FuelCells.ViewModel.DisplayedFuelCellItem.init(title: "Auto Gāze", toggleStatus: false)
			]
			
  	func displayListWithData(response: FuelTypeChooseList.FuelCells.Response) {
    	let viewModel = FuelTypeChooseList.FuelCells.ViewModel.init(displayedFuelCellItems: array)
    	viewController?.displayListWithData(viewModel: viewModel)
  	}
}
