//
//  FuelTypeChooseListModels.swift
//  fuelhunter
//
//  Created by Guntis on 05/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum FuelTypeChooseList {
  	// MARK: Use cases

	enum FuelCells {
		struct Request {
		}
		struct Response {
		}
		struct ViewModel {
			struct DisplayedFuelCellItem: Equatable {
				var title: String
				var toggleStatus: Bool = false
			}
			var displayedFuelCellItems: [DisplayedFuelCellItem]
		}
  	}
}
