//
//  SettingsWorker.swift
//  fuelhunter
//
//  Created by Guntis on 27/06/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SettingsWorker {
  	func returnSettingsCellsDataArray() -> Settings.SettingsList.Response {
		
		let companyNames = "NESTE"
		let fuelTypeNames = "DD"
		let gpsIsEnabledStatus = true
		let pushNotifIsEnabledStatus = false
		
		return Settings.SettingsList.Response.init(companyNames: companyNames, fuelTypeNames: fuelTypeNames, gpsIsEnabledStatus: gpsIsEnabledStatus, pushNotifIsEnabledStatus: pushNotifIsEnabledStatus)
  	}
  	
//  	func returnSettingsCellPressedResponse(fromId id: String) -> Settings.SettingsCellPressed.Response {
//  		if id == "0" {
//  			Settings.SettingsCellPressed.Response.init()
//  		} else {
//  		
//  		}
//  	}
}
