//
//  SettingsModels.swift
//  fuelhunter
//
//  Created by Guntis on 27/06/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Settings {
  	// MARK: Use cases
	
	enum SettingsListCellType {
		case fuelCompanyCell
		case fuelTypeCell
		case gpsCell
		case pushNotifCell
		case appLanguageCell
		case aboutAppCell
	}
	
	enum SettingsList {
		struct Request {
		}
		struct Response {
			let companyNames: String
			let fuelTypeNames: String
			let gpsIsEnabledStatus: Bool
			let pushNotifIsEnabledStatus: Bool
		}
		struct ViewModel {
			struct DisplayedSettingsCell: Equatable {
				var settingsListCellType: SettingsListCellType
				var title: String
				var description: String
				var shouldShowToggle: Bool
				var shouldShowAccessory: Bool
				var toggleStatus: Bool = false
			}
			var displayedSettingsCells: [DisplayedSettingsCell]
		}
  	}
}
