//
//  SettingsRouter.swift
//  fuelhunter
//
//  Created by Guntis on 27/06/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SettingsRoutingLogic {
  	@objc func routeToCompanyChooseScene()
  	@objc func routeToFuelTypeScene()
  	@objc func routeToLanguageChooseScene()
  	@objc func routeToAboutScene()
}

protocol SettingsDataPassing {
  	var dataStore: SettingsDataStore? { get }
}

class SettingsRouter: NSObject, SettingsRoutingLogic, SettingsDataPassing {
  	weak var viewController: SettingsViewController?
  	var dataStore: SettingsDataStore?

	// MARK: Routing

	@objc func routeToCompanyChooseScene() {
		let storyboard = UIStoryboard(name: "Main", bundle: nil)
  		let destinationVC = storyboard.instantiateViewController(withIdentifier: "companiesChooseViewController") as! CompaniesChooseListViewController
  		navigateToScene(source: viewController!, destination: destinationVC)
  	}
	
  	@objc func routeToFuelTypeScene() {
  	
  	}
  	
  	@objc func routeToLanguageChooseScene() {
  	
  	}
  	
  	@objc func routeToAboutScene() {
  	
  	}
  	
	// MARK: Navigation  
	func navigateToScene(source: UIViewController, destination: UIViewController)
  	{
		source.navigationItem.backBarButtonItem = UIBarButtonItem(title: "", style: .plain, target: nil, action: nil)
		source.show(destination, sender: nil)
  	}  
}
