//
//  SettingsRouter.swift
//  fuelhunter
//
//  Created by Guntis on 27/06/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsRoutingLogic {
  	func routeToCompanyChooseScene()
  	func routeToFuelTypeScene()
  	func routeToLanguageChooseScene()
  	func routeToAboutScene()
  	func presentNotifSetUpScene(response: Settings.PushNotif.Response)
}

protocol SettingsDataPassing {
  	var dataStore: SettingsDataStore? { get }
}

class SettingsRouter: NSObject, SettingsRoutingLogic, SettingsDataPassing {
  	weak var viewController: SettingsViewController?
  	var dataStore: SettingsDataStore?

	// MARK: Routing

	func routeToCompanyChooseScene() {
		let storyboard = UIStoryboard(name: "Main", bundle: nil)
  		let destinationVC = storyboard.instantiateViewController(withIdentifier: "companiesChooseViewController") as! CompaniesChooseListViewController
  		navigateToScene(source: viewController!, destination: destinationVC)
  	}
	
  	func routeToFuelTypeScene() {
  		let storyboard = UIStoryboard(name: "Main", bundle: nil)
  		let destinationVC = storyboard.instantiateViewController(withIdentifier: "fuelTypeChooseViewController") as! FuelTypeChooseListViewController
  		navigateToScene(source: viewController!, destination: destinationVC)
  	}
  	
  	func routeToLanguageChooseScene() {
  		let storyboard = UIStoryboard(name: "Main", bundle: nil)
  		let destinationVC = storyboard.instantiateViewController(withIdentifier: "appLanguageViewController") as! AppLanguageViewController
  		navigateToScene(source: viewController!, destination: destinationVC)
  	}
  	
  	func routeToAboutScene() {
  		let storyboard = UIStoryboard(name: "Main", bundle: nil)
  		let destinationVC = storyboard.instantiateViewController(withIdentifier: "aboutAppViewController") as! AboutAppViewController
  		navigateToScene(source: viewController!, destination: destinationVC)
  	}
  	
  	func presentNotifSetUpScene(response: Settings.PushNotif.Response) {
  		let storyboard = UIStoryboard(name: "Main", bundle: nil)
  		let destinationVC = storyboard.instantiateViewController(withIdentifier: "pushNotifSetupViewController") as! PushNotifSetupViewController
  		destinationVC.router?.previousViewController = viewController!
  		destinationVC.providesPresentationContextTransitionStyle = true
		destinationVC.definesPresentationContext = true
		destinationVC.modalPresentationStyle=UIModalPresentationStyle.overCurrentContext
		viewController!.present(destinationVC, animated: true) { }
  	}
  	
	func navigateToScene(source: UIViewController, destination: UIViewController) {
		source.navigationItem.backBarButtonItem = UIBarButtonItem(title: "", style: .plain, target: nil, action: nil)
		source.show(destination, sender: nil)
  	}  
}
