//
//  SettingsPresenter.swift
//  fuelhunter
//
//  Created by Guntis on 27/06/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsPresentationLogic {
  	func presentSettingsListWithData(response: Settings.SettingsList.Response)
}

class SettingsPresenter: SettingsPresentationLogic {
  	weak var viewController: SettingsDisplayLogic?

  	// MARK: Do something

  	func presentSettingsListWithData(response: Settings.SettingsList.Response) {
  	
  		let companyNames = response.companyNames
		let fuelTypeNames = response.fuelTypeNames
		let gpsIsEnabledStatus = response.gpsIsEnabledStatus
		let pushNotifIsEnabledStatus = response.pushNotifIsEnabledStatus
		
		let array =  [
			Settings.SettingsList.ViewModel.DisplayedSettingsCell.init(settingsListCellType: .fuelCompanyCell, title: companyNames, description: "Atzīmē, kuras uzpildes kompānijas vēlies redzēt sarakstā", shouldShowToggle: false, shouldShowAccessory: true, toggleStatus: false),
			Settings.SettingsList.ViewModel.DisplayedSettingsCell.init(settingsListCellType: .fuelTypeCell, title: fuelTypeNames, description: "Aktuālais degvielas veids", shouldShowToggle: false, shouldShowAccessory: true, toggleStatus: false),
			Settings.SettingsList.ViewModel.DisplayedSettingsCell.init(settingsListCellType: .gpsCell, title: "GPS", description: "Izmantot GPS, lai attēlotu lētākās cenas Tavas lokācijas tuvumā", shouldShowToggle: true, shouldShowAccessory: false, toggleStatus: gpsIsEnabledStatus),
			Settings.SettingsList.ViewModel.DisplayedSettingsCell.init(settingsListCellType: .pushNotifCell, title: "Paziņojumi", description: "Saņemt paziņojumu telefonā, kad samazinās degvielas cena par 1 centu", shouldShowToggle: true, shouldShowAccessory: false, toggleStatus: pushNotifIsEnabledStatus),
			Settings.SettingsList.ViewModel.DisplayedSettingsCell.init(settingsListCellType: .appLanguageCell, title: "Aplikācijas valoda", description: "Izmaini aplikācijas valodu", shouldShowToggle: false, shouldShowAccessory: true, toggleStatus: false),
			Settings.SettingsList.ViewModel.DisplayedSettingsCell.init(settingsListCellType: .aboutAppCell, title: "Par aplikāciju", description: "Kā tas strādā", shouldShowToggle: false, shouldShowAccessory: true, toggleStatus: false)]
  	
  	
    	let viewModel = Settings.SettingsList.ViewModel(displayedSettingsCells: array)
    	viewController?.displaySettingsList(viewModel: viewModel)
    	
  	}
}
