//
//  IntroNotifSetUpInteractor.swift
//  fuelhunter
//
//  Created by Guntis on 25/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol IntroNotifSetUpBusinessLogic {
  	func userAskedForNotifAccess(request: IntroNotifSetUp.Something.Request)
}

protocol IntroNotifSetUpDataStore {
}

class IntroNotifSetUpInteractor: IntroNotifSetUpBusinessLogic, IntroNotifSetUpDataStore {
  	var presenter: IntroNotifSetUpPresentationLogic?

  	// MARK: IntroNotifSetUpBusinessLogic

  	func userAskedForNotifAccess(request: IntroNotifSetUp.Something.Request) {
  		AppSettingsWorker.shared.notifSwitchWasPressed { [weak self] in
  			// If we have auth
			if AppSettingsWorker.shared.notificationsAuthorisationStatus == .authorized
  				&& AppSettingsWorker.shared.getNotifIsEnabled() == true {
				let storedCentsCount = AppSettingsWorker.shared.getStoredNotifCentsCount()
				let response = IntroNotifSetUp.PushNotif.Response(storedNotifCentsCount: storedCentsCount)
				self?.presenter?.showNotifSetUp(response: response)
			} else {
				ScenesManager.shared.advanceAppSceneState()
			}
		}
  	}
}
