//
//  IntroNotifSetUpModels.swift
//  fuelhunter
//
//  Created by Guntis on 25/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum IntroNotifSetUp {
  	// MARK: Use cases
	enum PushNotif {
		struct Request {
		}
		struct Response {
			let storedNotifCentsCount: Int
		}
		struct ViewModel {
		}
	}
	enum Something {
		struct Request {
		}
		struct Response {
		}
		struct ViewModel {
		}
  	}
}
