//
//  IntroNotifSetUpInteractor.swift
//  fuelhunter
//
//  Created by Guntis on 25/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol IntroNotifSetUpBusinessLogic {
  	func doSomething(request: IntroNotifSetUp.Something.Request)
  	func userAskedForNotifAccess(request: IntroNotifSetUp.Something.Request)
}

protocol IntroNotifSetUpDataStore {
  	//var name: String { get set }
}

class IntroNotifSetUpInteractor: IntroNotifSetUpBusinessLogic, IntroNotifSetUpDataStore {
  	var presenter: IntroNotifSetUpPresentationLogic?
  	var worker: IntroNotifSetUpWorker?
  	var appSettingsWorker = AppSettingsWorker()
  	//var name: String = ""

  	// MARK: Do something

  	func doSomething(request: IntroNotifSetUp.Something.Request) {
    	worker = IntroNotifSetUpWorker()
    	worker?.doSomeWork()

    	let response = IntroNotifSetUp.Something.Response()
    	presenter?.presentSomething(response: response)
  	}
  	
  	func userAskedForNotifAccess(request: IntroNotifSetUp.Something.Request) {
			appSettingsWorker.notifSwitchWasPressed { result in 
				switch result {
  				case .success(let data):
  					// All good. 
					ScenesManager.shared.advanceAppSceneState()
					print(data)
				case .needsSetUp:
					let storedCentsCount = self.appSettingsWorker.getStoredNotifCentsCount()
					let response = IntroNotifSetUp.PushNotif.Response.init(storedNotifCentsCount: storedCentsCount)
					self.presenter?.showNotifSetUp(response: response)
  				case .failure(let error):
  					// Error. Update UI. Show error.
//  					let request = Settings.SettingsList.Request()
//  					self.getSettingsCellsData(request: request)
  					print(error)
  			}
		}
  	}
}
