//
//  IntroNotifSetUpPresenter.swift
//  fuelhunter
//
//  Created by Guntis on 25/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol IntroNotifSetUpPresentationLogic {
  	func presentSomething(response: IntroNotifSetUp.Something.Response)
  	func showNotifSetUp(response: IntroNotifSetUp.PushNotif.Response)
}

class IntroNotifSetUpPresenter: IntroNotifSetUpPresentationLogic {
  	weak var viewController: IntroNotifSetUpDisplayLogic?
	weak var router: IntroNotifSetUpRouter?
  	// MARK: Do something

  	func presentSomething(response: IntroNotifSetUp.Something.Response) {
    	let viewModel = IntroNotifSetUp.Something.ViewModel()
    	viewController?.displaySomething(viewModel: viewModel)
  	}
  	
  	func showNotifSetUp(response: IntroNotifSetUp.PushNotif.Response) {
  		router?.presentNotifSetUpScene(response: response)
  	}
}
