//
//  SettingsWorker.swift
//  fuelhunter
//
//  Created by Guntis on 27/06/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreData

class SettingsWorker {

	func getCompanyNames() -> String {
		let context = DataBaseManager.shared.mainManagedObjectContext()

		let fetchRequest: NSFetchRequest<CompanyEntity> = CompanyEntity.fetchRequest()

		fetchRequest.predicate = NSPredicate(format: "isEnabled == %i", true)

		let sort = NSSortDescriptor(key: "order", ascending: true)
		fetchRequest.sortDescriptors = [sort]

		do {
			let fetchedCompanies = try context.fetch(fetchRequest)

			if fetchedCompanies.isEmpty {
				// Problem, because at least Cheapest should be returned.
				return ""
			} else {
				var combinedString = ""
				for aCompany in fetchedCompanies {
					let companyName = aCompany.name ?? " "
					combinedString.append("\(companyName.localized()), ")
				}

				if combinedString.count > 0 { combinedString.removeLast() }
				if combinedString.count > 0 { combinedString.removeLast() }

				return combinedString
			}
		} catch let error {
			print("Something went wrong. \(error)")
		}

		return ""
	}
}
