//
//  AreasEditListPresenter.swift
//  fuelhunter
//
//  Created by Guntis on 27/06/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AreasEditListPresentationLogic {
  	func presentAreasListWithData(response: Areas.AreasEditList.Response)
}

class AreasEditListPresenter: AreasEditListPresentationLogic {
  	weak var viewController: AreasEditListDisplayLogic?
	weak var router: AreasEditListRouter?

  	// MARK: AreasEditListPresentationLogic

  	func presentAreasListWithData(response: Areas.AreasEditList.Response) {

		var array: [Areas.AreasEditList.ViewModel.DisplayedCell] = []

		for area in response.fetchedAreas {
			if area.isGPSArea {
				array.append(Areas.AreasEditList.ViewModel.DisplayedCell(id: Int(area.id), name: AppSettingsWorker.shared.getStoredLastGPSDetectedCityName(), description: "areas_gps_calculated_location".localized(), type: AreaType.areaTypeGPS))
			} else {

					// if 2 or more
					//"areas_fuel_companies".localized()

					// if 1
					//"areas_fuel_company".localized()

					// Description needs to be

					//  enabled company count + localized String


				var companies = Set<String>()
				let enabledStations = area.enabledStations?.allObjects ?? [AddressEntity]()

				for address in enabledStations as! [AddressEntity] {
					companies.insert("\(address.companyName ?? "")")
				}

				var description = ""

				if(companies.count == 0) {
					description = "areas_fuel_company_empty_description".localized()
				} else if(companies.count == 1) {
					description = "\(area.cityName!) - 1 \("areas_fuel_company".localized())"
				} else {
					description = "\(area.cityName!) - \(companies.count) \("areas_fuel_companies".localized())"
				}

				array.append(Areas.AreasEditList.ViewModel.DisplayedCell(id: Int(area.id), name: area.name!, description: description, type: AreaType.areaTypeAdded))
			}
		}

		array.append(Areas.AreasEditList.ViewModel.DisplayedCell(id: 900, name: "areas_create_new_area".localized(), description: "areas_create_new_area_description".localized(), type: AreaType.areaTypeNew))

    	let viewModel = Areas.AreasEditList.ViewModel(displayedCells: array)
    	viewController?.displayList(viewModel: viewModel)
  	}
}
