//
//  AreasEditListModels.swift
//  fuelhunter
//
//  Created by Guntis on 27/06/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Areas {

  	// MARK: Use cases

	enum AreasEditList {
		struct Request {
		}
		struct Response {
			var fetchedAreas: [AreasEntity]
		}
		struct ViewModel {
			struct DisplayedCell: Equatable {
				var id: Int
				var name: String
				var description: String
				var type: AreaType
			}
			var displayedCells: [DisplayedCell]
		}
  	}
}
