//
//  AreasEditListPresenter.swift
//  fuelhunter
//
//  Created by Guntis on 27/06/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AreasEditListPresentationLogic {
  	func presentAreasListWithData(response: Areas.AreasEditList.Response)
}

class AreasEditListPresenter: AreasEditListPresentationLogic {
  	weak var viewController: AreasEditListDisplayLogic?
	weak var router: AreasEditListRouter?

  	// MARK: AreasEditListPresentationLogic

  	func presentAreasListWithData(response: Areas.AreasEditList.Response) {

		var array: [Areas.AreasEditList.ViewModel.DisplayedCell] = []

		for area in response.fetchedAreas {
			if area.isGPSArea {
				array.append(Areas.AreasEditList.ViewModel.DisplayedCell(id: Int(area.id), name: AppSettingsWorker.shared.getStoredLastGPSDetectedCityName(), description: "areas_gps_calculated_location".localized(), type: AreaType.areaTypeGPS))
			} else {

					// if 2 or more
					//"areas_fuel_companies".localized()

					// if 1
					//"areas_fuel_company".localized()
					
				array.append(Areas.AreasEditList.ViewModel.DisplayedCell(id: Int(area.id), name: area.name!, description: "Rīga - 2 degvielas uzpildes kompānijas".localized(), type: AreaType.areaTypeAdded))
			}
		}

		array.append(Areas.AreasEditList.ViewModel.DisplayedCell(id: 100, name: "areas_create_new_area".localized(), description: "areas_create_new_area_description".localized(), type: AreaType.areaTypeNew))

    	let viewModel = Areas.AreasEditList.ViewModel(displayedCells: array)
    	viewController?.displayList(viewModel: viewModel)
  	}
}
