//
//  AreasEditListRouter.swift
//  fuelhunter
//
//  Created by Guntis on 27/06/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MessageUI
import CoreData
import FirebaseCrashlytics
import CoreLocation

protocol AreasEditListRoutingLogic {
	func userPressedOnAreaWithId(withItemId id: Int)
	func routeToSetUp()
}

protocol AreasEditListDataPassing {
  	var dataStore: AreasEditListDataStore? { get }
}

class AreasEditListRouter: NSObject, AreasEditListRoutingLogic, AreasEditListDataPassing {
  	weak var viewController: AreasEditListViewController?
  	var dataStore: AreasEditListDataStore?

	// MARK: AreasEditListRoutingLogic

	func userPressedOnAreaWithId(withItemId id: Int) {
		let page = AreaEditPageViewController()
		page.router?.dataStore?.areaId = id
		navigateToScene(source: viewController!, destination: page)
	}

	func routeToSetUp() {
		let destinationVC = AreaSetUpPageViewController()
//		destinationVC.router?.previousViewController = self
  		destinationVC.providesPresentationContextTransitionStyle = true
		destinationVC.definesPresentationContext = true
		destinationVC.modalPresentationStyle=UIModalPresentationStyle.overCurrentContext
		viewController!.present(destinationVC, animated: true) { }
	}

	// MARK: Functions

	private func navigateToScene(source: UIViewController, destination: UIViewController) {
		source.navigationItem.backBarButtonItem = UIBarButtonItem(title: "", style: .plain, target: nil, action: nil)
		source.show(destination, sender: nil)
  	}
}
