//
//  FuelTypeChooseListViewController.swift
//  fuelhunter
//
//  Created by Guntis on 05/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FuelTypeChooseListDisplayLogic: class {
  	func displayListWithData(viewModel: FuelTypeChooseList.FuelCells.ViewModel)
}

class FuelTypeChooseListViewController: UIViewController, FuelTypeChooseListDisplayLogic, FuelTypeChooseListLayoutViewLogic {
	
  	var interactor: FuelTypeChooseListBusinessLogic?
  	var router: (NSObjectProtocol & FuelTypeChooseListRoutingLogic & FuelTypeChooseListDataPassing)?
	var layoutView: FuelTypeChooseListLayoutView!
  	
  	// MARK: Object lifecycle

  	override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    	super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    	setup()
  	}

  	required init?(coder aDecoder: NSCoder) {
    	super.init(coder: aDecoder)
    	setup()
  	}

  	// MARK: Setup

  	private func setup() {
		let viewController = self
		let interactor = FuelTypeChooseListInteractor()
		let presenter = FuelTypeChooseListPresenter()
		let router = FuelTypeChooseListRouter()
		viewController.interactor = interactor
		viewController.router = router
		interactor.presenter = presenter
		presenter.viewController = viewController
		router.viewController = viewController
		router.dataStore = interactor
  	}

  	// MARK: View lifecycle

  	override func viewDidLoad() {
    	super.viewDidLoad()
    	
		self.title = "Degvielas veids"
    	self.view.backgroundColor = .white
		setUpView()
    	getFuelTypesListData()
  	}
	
	override func viewWillDisappear(_ animated: Bool) {
		super.viewWillDisappear(animated)
		interactor?.reCheckFuelTypes()
	}
	override func viewDidAppear(_ animated: Bool) {
		super.viewDidAppear(animated)
	}
	
	// MARK: Set up
	
	func setUpView() {
		layoutView = FuelTypeChooseListLayoutView.init(frame: CGRect.init(x: 0, y: 0, width: self.view.frame.width, height: 100))
		self.view.addSubview(layoutView)
		layoutView.topAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.topAnchor).isActive = true
        layoutView.leftAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.leftAnchor).isActive = true
        layoutView.rightAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.rightAnchor).isActive = true
        layoutView.bottomAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.bottomAnchor).isActive = true
		layoutView.controller = self
	}
	
  	// MARK: Do something
  	
  	func getFuelTypesListData() {
    	let request = FuelTypeChooseList.FuelCells.Request()
    	interactor?.getFuelTypesListData(request: request)
  	}

  	func displayListWithData(viewModel: FuelTypeChooseList.FuelCells.ViewModel) {
    	layoutView.data = viewModel.displayedFuelCellItems
    	layoutView.tableView.reloadData()
		layoutView.tableView.layoutIfNeeded()
  	}

	// MARK: FuelTypeChooseListLayoutViewLogic 

	func switchWasPressedFor(fuelType: FuelType, withState state: Bool) {
		let request = FuelTypeChooseList.SwitchToggled.Request.init(fuelType: fuelType, state: state)
		interactor?.userToggledFuelType(request: request)
	}
}
