//
//  FuelTypeChooseListRouter.swift
//  fuelhunter
//
//  Created by Guntis on 05/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FuelTypeChooseListRoutingLogic {
  	//func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol FuelTypeChooseListDataPassing {
  	var dataStore: FuelTypeChooseListDataStore? { get }
}

class FuelTypeChooseListRouter: NSObject, FuelTypeChooseListRoutingLogic, FuelTypeChooseListDataPassing {
  	weak var viewController: FuelTypeChooseListViewController?
  	var dataStore: FuelTypeChooseListDataStore?
}
