//
//  FuelTypeChooseListPresenter.swift
//  fuelhunter
//
//  Created by Guntis on 05/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FuelTypeChooseListPresentationLogic {
  	func presentData(response: FuelTypeChooseList.FuelCells.Response)
}

class FuelTypeChooseListPresenter: FuelTypeChooseListPresentationLogic {
  	weak var viewController: FuelTypeChooseListDisplayLogic?

  	// MARK: Do something
		
  	func presentData(response: FuelTypeChooseList.FuelCells.Response) {
  	
  		let array =  [
			FuelTypeChooseList.FuelCells.ViewModel.DisplayedFuelCellItem.init(fuelType: .typeDD, title: "DD | Dīzeļdegviela", toggleStatus: response.statusOfDD),
			FuelTypeChooseList.FuelCells.ViewModel.DisplayedFuelCellItem.init(fuelType: .typeDDPro, title: "DD | Pro Dīzeļdegviela", toggleStatus: response.statusOfProDD),
			FuelTypeChooseList.FuelCells.ViewModel.DisplayedFuelCellItem.init(fuelType: .type95, title: "95 | Benzīns", toggleStatus: response.statusOf95),
			FuelTypeChooseList.FuelCells.ViewModel.DisplayedFuelCellItem.init(fuelType: .type98, title: "98 | Benzīns", toggleStatus: response.statusOf98),
			FuelTypeChooseList.FuelCells.ViewModel.DisplayedFuelCellItem.init(fuelType: .typeGas, title: "Auto Gāze", toggleStatus: response.statusOfGas)
			]
			
    	let viewModel = FuelTypeChooseList.FuelCells.ViewModel.init(displayedFuelCellItems: array)
    	viewController?.displayListWithData(viewModel: viewModel)
  	}
}
