//
//  AreaSetUpPageModels.swift
//  fuelhunter
//
//  Created by Guntis on 10/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AreaSetUpPage {
  	// MARK: Use cases
	enum SetUp {
		struct Request {
		}
		struct Response {
//			var value: Int
//			var convertedValue: String
//			var minValue: Int
//			var maxValue: Int
//			var sortedCities: [CityAndDistance]
//			var selectedCityName: String
		}
		struct ViewModel {
			struct DisplayedItem: Equatable {
//				var description: String
//				var value: Int
//				var minValue: Int
//				var maxValue: Int
//				var sortedCities: [CityAndDistance]
//				var selectedCityName: String
			}
			var displayedItem: DisplayedItem
		}
  	}

  	enum AreaEditPage {
		struct Request {
		}
		struct Response {
			var fetchedArea: AreasEntity
		}
		struct ViewModel {
			struct DisplayedCell: Equatable {
				var name: String
				var toggleOrCheckmarkIsOn: Bool
				var iconName: String
				var description: String
				var accessoryType: CellAccessoryType
				var functionalityType: CellFunctionalityType
			}
			var displayedCells: [[DisplayedCell]]
//			var areaName: String
		}
  	}
}
