//
//  AreaSetUpPagePresenter.swift
//  fuelhunter
//
//  Created by Guntis on 10/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AreaSetUpPagePresentationLogic {
  	func presentData(response: AreaSetUpPage.SetUp.Response)
  	func presentSecondData(response: AreaSetUpPage.UserSelectedNext.Response)
  	func returnBackToPreviousViewController()
}

class AreaSetUpPagePresenter: AreaSetUpPagePresentationLogic {
  	weak var viewController: AreaSetUpPageDisplayLogic?
	weak var router: AreaSetUpPageRouter?

  	// MARK: AreaSetUpPagePresentationLogic

  	func presentData(response: AreaSetUpPage.SetUp.Response) {

		let viewModelFirst = AreaSetUpPage.SetUp.ViewModel.init(displayedItem: AreaSetUpPage.SetUp.ViewModel.DisplayedItem.init())
    	viewController?.updateFirstViewData(viewModel: viewModelFirst)
  	}

  	func presentSecondData(response: AreaSetUpPage.UserSelectedNext.Response) {

		var arrayBasics: [AreaSetUpPage.AreaEditPage.ViewModel.DisplayedCell] = []
		var arrayCompanies: [AreaSetUpPage.AreaEditPage.ViewModel.DisplayedCell] = []

		arrayBasics.append(AreaSetUpPage.AreaEditPage.ViewModel.DisplayedCell.init(name: response.areaName, toggleOrCheckmarkIsOn: false, iconName:"", description: "areas_name_title_description".localized(), accessoryType: .cellAccessoryTypeName, functionalityType: .cellFunctionalityTypeName))

		arrayBasics.append(AreaSetUpPage.AreaEditPage.ViewModel.DisplayedCell.init(name: "areas_cheapest_only_title".localized(), toggleOrCheckmarkIsOn: response.cheapestPriceIsOn, iconName:"", description: "areas_cheapest_only_description".localized(), accessoryType: .cellAccessoryTypeToggle, functionalityType: .cellFunctionalityTypeCheapestOnly))


		for companyEntry in response.companyEntries {
			let name = companyEntry.stationCount == 1 ? "1 degvielas uzpildes stacija" : "\(companyEntry.stationCount) degvielas uzpildes stacijas"
			
			arrayCompanies.append(AreaSetUpPage.AreaEditPage.ViewModel.DisplayedCell.init(name: companyEntry.name, toggleOrCheckmarkIsOn: companyEntry.enabled, iconName:companyEntry.imageName, description: name, accessoryType: .cellAccessoryTypeCheckMark, functionalityType: .cellFunctionalityTypeCompany))
		}

		let resultArray: [[AreaSetUpPage.AreaEditPage.ViewModel.DisplayedCell]] = [arrayBasics, arrayCompanies];

    	let viewModel = AreaSetUpPage.AreaEditPage.ViewModel(displayedCells: resultArray, newAreaName: response.areaName)
    	viewController?.updateSecondViewData(viewModel: viewModel)
  	}

  	func returnBackToPreviousViewController() {
  		router?.dismissCurrentViewController()
  	}
}
