//
//  AboutAppPresenter.swift
//  fuelhunter
//
//  Created by Guntis on 07/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AboutAppPresentationLogic {
  	func presentSomething(response: AboutApp.CompanyCells.Response)
}

class AboutAppPresenter: AboutAppPresentationLogic {
  	weak var viewController: AboutAppDisplayLogic?

  	// MARK: AboutAppPresentationLogic

  	func presentSomething(response:  AboutApp.CompanyCells.Response) {

		let array =  [
			AboutApp.CompanyCells.ViewModel.DisplayedCompanyCellItem.init(title: "Neste", description: "company_type_neste_description", imageName: "neste_logo", enabled: true),
			AboutApp.CompanyCells.ViewModel.DisplayedCompanyCellItem.init(title: "Circle K", description: "company_type_circle_k_description", imageName: "circle_k_logo", enabled: true),
			AboutApp.CompanyCells.ViewModel.DisplayedCompanyCellItem.init(title: "Kool", description: "company_type_kool_description", imageName: "kool_logo", enabled: true),
			AboutApp.CompanyCells.ViewModel.DisplayedCompanyCellItem.init(title: "Latvijas Nafta", description: "company_type_ln_description", imageName: "ln_logo", enabled: true),
			AboutApp.CompanyCells.ViewModel.DisplayedCompanyCellItem.init(title: "Virši", description: "company_type_virsi_description", imageName: "virshi_logo", enabled: true),
			AboutApp.CompanyCells.ViewModel.DisplayedCompanyCellItem.init(title: "Gotika auto", description: "company_type_gotika_description", imageName: "gotika_logo", enabled: true)
			]

    	let viewModel = AboutApp.CompanyCells.ViewModel.init(displayedCompanyCellItems: array)
    	viewController?.displayData(viewModel: viewModel)
  	}
}
