//
//  AboutAppPresenter.swift
//  fuelhunter
//
//  Created by Guntis on 07/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AboutAppPresentationLogic {
  	func presentData(response: AboutApp.CompanyCells.Response)
}

class AboutAppPresenter: AboutAppPresentationLogic {
  	weak var viewController: AboutAppDisplayLogic?

  	// MARK: AboutAppPresentationLogic

  	func presentData(response:  AboutApp.CompanyCells.Response) {

		var array = [AboutApp.CompanyCells.ViewModel.DisplayedCompanyCellItem]()

		for company in response.fetchedCompanies {
			let title = company.name ?? ""
			let imageName = company.logoName ?? ""
			array.append(AboutApp.CompanyCells.ViewModel.DisplayedCompanyCellItem(title: title, imageName: imageName))
		}

    	let viewModel = AboutApp.CompanyCells.ViewModel(displayedCompanyCellItems: array)
    	viewController?.displayData(viewModel: viewModel)
  	}
}
