//
//  AboutAppRouter.swift
//  fuelhunter
//
//  Created by Guntis on 07/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AboutAppRoutingLogic {
}

protocol AboutAppDataPassing {
  	var dataStore: AboutAppDataStore? { get }
}

class AboutAppRouter: NSObject, AboutAppRoutingLogic, AboutAppDataPassing {
  	weak var viewController: AboutAppViewController?
  	var dataStore: AboutAppDataStore?
}
