//
//  AboutAppPresenter.swift
//  fuelhunter
//
//  Created by Guntis on 07/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AboutAppPresentationLogic {
  	func presentSomething(response: AboutApp.CompanyCells.Response)
}

class AboutAppPresenter: AboutAppPresentationLogic {
  	weak var viewController: AboutAppDisplayLogic?

  	// MARK: AboutAppPresentationLogic

  	func presentSomething(response:  AboutApp.CompanyCells.Response) {

		let array =  [
			AboutApp.CompanyCells.ViewModel.DisplayedCompanyCellItem.init(title: "Neste", description: "Lētākā Degviela Rīgā.", imageName: "neste_logo", enabled: true),
			AboutApp.CompanyCells.ViewModel.DisplayedCompanyCellItem.init(title: "Circle K", description: "Lētākā Degviela Rīgā.", imageName: "circle_k_logo", enabled: true),
			AboutApp.CompanyCells.ViewModel.DisplayedCompanyCellItem.init(title: "Kool", description: "Zemākās cenas DUS tīklā Latvijā.", imageName: "kool_logo", enabled: true),
			AboutApp.CompanyCells.ViewModel.DisplayedCompanyCellItem.init(title: "Latvijas Nafta", description: "Zemākās cenas DUS tīklā Latvijā, pa reģioniem (Rīgas rajons, Liepājas rajons, Ventspils rajons, Zemgale, Vidzeme, Latgale).", imageName: "ln_logo", enabled: true),
			AboutApp.CompanyCells.ViewModel.DisplayedCompanyCellItem.init(title: "Virši", description: "Lētākā degviela Rīgā un Pierīgā.", imageName: "virshi_logo", enabled: true),
			AboutApp.CompanyCells.ViewModel.DisplayedCompanyCellItem.init(title: "Gotika auto", description: "Zemākās cenas DUS tīklā Latvijā.", imageName: "gotika_logo", enabled: true)
			]

    	let viewModel = AboutApp.CompanyCells.ViewModel.init(displayedCompanyCellItems: array)
    	viewController?.displayData(viewModel: viewModel)
  	}
}
