//
//  AppLanguageWorker.swift
//  fuelhunter
//
//  Created by Guntis on 05/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class AppLanguageWorker {
  	func getStatusOfEnabledFuelTypes() -> AppLanguage.GetLanguage.Response {
  		let currentlyActiveLanguage: AppLanguage.LanguageType = .languageLatvian
  		return AppLanguage.GetLanguage.Response.init(activeLanguage: currentlyActiveLanguage)
  	}
}
