//
//  AppLanguageViewController.swift
//  fuelhunter
//
//  Created by Guntis on 05/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AppLanguageDisplayLogic: class {
  	func presentLanguageList(viewModel: AppLanguage.GetLanguage.ViewModel)
}

class AppLanguageViewController: UIViewController, AppLanguageDisplayLogic, UITableViewDataSource, UITableViewDelegate {
  	var interactor: AppLanguageBusinessLogic?
  	var router: (NSObjectProtocol & AppLanguageRoutingLogic & AppLanguageDataPassing)?
	var data = [AppLanguage.GetLanguage.ViewModel.DisplayedLanguageCellItem]()
  	var activateShadowUpdates = false
  	
	@IBOutlet weak var tableView: UITableView!
	@IBOutlet weak var navBarBottomShadow: UIImageView!
	@IBOutlet weak var tableViewBottomShadow: UIImageView!
	
  	// MARK: Object lifecycle

  	override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    	super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    	setup()
  	}

  	required init?(coder aDecoder: NSCoder) {
    	super.init(coder: aDecoder)
    	setup()
  	}

  	// MARK: Setup

  	private func setup() {
		let viewController = self
		let interactor = AppLanguageInteractor()
		let presenter = AppLanguagePresenter()
		let router = AppLanguageRouter()
		viewController.interactor = interactor
		viewController.router = router
		interactor.presenter = presenter
		presenter.viewController = viewController
		router.viewController = viewController
		router.dataStore = interactor
  	}

  	// MARK: View lifecycle

  	override func viewDidLoad() {
    	super.viewDidLoad()
    	self.title = "Aplikācijas valoda"
    	
    	
    	self.view.backgroundColor = .white
		tableView.delegate = self
    	tableView.dataSource = self
		tableView.separatorStyle = .none
    	tableView.contentInset = UIEdgeInsets.init(top: 22, left: 0, bottom: 10, right: 0)
    	let nib = UINib.init(nibName: "LanguageListCell", bundle: nil)
    	tableView.register(nib, forCellReuseIdentifier: "cell")
    	
    	getLanaguageListData()
  	}

	override func viewDidAppear(_ animated: Bool) {
		super.viewDidAppear(animated)
		activateShadowUpdates = true
	}
		
	// MARK: Table view
	
	func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
		return data.count
	}

	func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {

		if let cell = tableView.dequeueReusableCell(
		   withIdentifier: "cell",
		   for: indexPath
		) as? LanguageListCell {
		
			let aData = self.data[indexPath.row]
			cell.selectionStyle = .none
			cell.titleLabel.text = aData.languageName
			cell.descriptionLabel.text = aData.languageNameTranslated
			
			if aData.currentlyActive == true {
				cell.checkBoxImageView.isHidden = false
			} else {
				cell.checkBoxImageView.isHidden = true
			}
			
			if self.data.count == 1 {
				cell.setAsCellType(cellType: .single)
			} else {
				if self.data.first == aData {
					cell.setAsCellType(cellType: .top)
				} else if self.data.last == aData {
					cell.setAsCellType(cellType: .bottom)
				} else {
					cell.setAsCellType(cellType: .middle)
				}
			}
			return cell
		} else {
			// Problem
			return UITableViewCell.init()
		}
	}
	
	func tableView(_ tableView: UITableView, heightForFooterInSection section: Int) -> CGFloat {
	
		return 0
	}

	func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {

	}

	func scrollViewDidScroll(_ scrollView: UIScrollView) {
		if activateShadowUpdates == true {
			adjustVisibilityOfShadowLines()
		}
	}
	
	func adjustVisibilityOfShadowLines() {
		let alfa = min(50, max(0, tableView.contentOffset.y+20))/50.0
		
		navBarBottomShadow.alpha = alfa
		
		let value = tableView.contentOffset.y+tableView.frame.size.height-tableView.contentInset.bottom-tableView.contentInset.top

		let alfa2 = min(50, max(0, tableView.contentSize.height-value-22))/50.0
		
		tableViewBottomShadow.alpha = alfa2
	}

  	// MARK: Do something

  	func getLanaguageListData() {
    	let request = AppLanguage.GetLanguage.Request()
    	interactor?.getLanaguageListData(request: request)
  	}

  	func presentLanguageList(viewModel: AppLanguage.GetLanguage.ViewModel) {
    	data = viewModel.displayedLanguageCellItems
    	tableView.reloadData()
		tableView.layoutIfNeeded()
		adjustVisibilityOfShadowLines()
  	}
}
