//
//  CompaniesChooseListInteractor.swift
//  fuelhunter
//
//  Created by Guntis on 04/07/2019.
//  Copyright (c) 2019 myEmerg. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CompaniesChooseListBusinessLogic {
  	func doSomething(request: CompaniesChooseList.Something.Request)
}

protocol CompaniesChooseListDataStore {
  	//var name: String { get set }
}

class CompaniesChooseListInteractor: CompaniesChooseListBusinessLogic, CompaniesChooseListDataStore {
  	var presenter: CompaniesChooseListPresentationLogic?
  	var worker: CompaniesChooseListWorker?
  	//var name: String = ""

  	// MARK: Do something

  	func doSomething(request: CompaniesChooseList.Something.Request) {
    	worker = CompaniesChooseListWorker()
    	worker?.doSomeWork()

    	let response = CompaniesChooseList.Something.Response()
    	presenter?.presentSomething(response: response)
  	}
}
