//
//  CompaniesChooseListPresenter.swift
//  fuelhunter
//
//  Created by Guntis on 04/07/2019.
//  Copyright (c) 2019 myEmerg. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CompaniesChooseListPresentationLogic {
  	func presentSomething(response: CompaniesChooseList.Something.Response)
}

class CompaniesChooseListPresenter: CompaniesChooseListPresentationLogic {
  	weak var viewController: CompaniesChooseListDisplayLogic?

  	// MARK: Do something

  	func presentSomething(response: CompaniesChooseList.Something.Response) {
    	let viewModel = CompaniesChooseList.Something.ViewModel()
    	viewController?.displaySomething(viewModel: viewModel)
  	}
}
