//
//  CompaniesChooseListWorker.swift
//  fuelhunter
//
//  Created by Guntis on 04/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CompaniesChooseListWorker {
  	func getStatusOfEnabledCompanies() -> CompaniesChooseList.CompanyCells.Response {
  	
		let statusOfCheapestCompany = false
		let statusOfNeste = true
		let statusOfCircleK = true
		let statusOfKool = true
		let statusOfLatvijasNafta = false
		let statusOfViada = false
		let statusOfVirsi = false
		let statusOfGotika = false
		let statusOfAstarte = false
		let statusOfDinaz = false
		let statusOfLatvijasPropanaGaze = false
		
		return CompaniesChooseList.CompanyCells.Response.init(companyCheapestStatus: statusOfCheapestCompany, companyNesteStatus: statusOfNeste, companyCircleKStatus: statusOfCircleK, companyKoolStatus: statusOfKool, companyLatvijasNaftaStatus: statusOfLatvijasNafta, companyViadaStatus: statusOfViada, companyVirsiStatus: statusOfVirsi, companyGotikaStatus: statusOfGotika, companyAstarteStatus: statusOfAstarte, companyDinazStatus: statusOfDinaz, companyLatvijasPropanaGazeStatus: statusOfLatvijasPropanaGaze)
  	}
}
