//
//  IntroGPSSetUpRouter.swift
//  fuelhunter
//
//  Created by Guntis on 02/08/2019.
//  Copyright (c) 2019 myEmerg. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol IntroGPSSetUpRoutingLogic {
  	//func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol IntroGPSSetUpDataPassing {
  	var dataStore: IntroGPSSetUpDataStore? { get }
}

class IntroGPSSetUpRouter: NSObject, IntroGPSSetUpRoutingLogic, IntroGPSSetUpDataPassing {
  	weak var viewController: IntroGPSSetUpViewController?
  	var dataStore: IntroGPSSetUpDataStore?

	// MARK: Routing

	//func routeToSomewhere(segue: UIStoryboardSegue?)
	//{
	//  if let segue = segue {
	//    let destinationVC = segue.destination as! SomewhereViewController
	//    var destinationDS = destinationVC.router!.dataStore!
	//    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
	//  } else {
	//    let storyboard = UIStoryboard(name: "Main", bundle: nil)
	//    let destinationVC = storyboard.instantiateViewController(withIdentifier:
	//   "SomewhereViewController") as! SomewhereViewController
	//    var destinationDS = destinationVC.router!.dataStore!
	//    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
	//    navigateToSomewhere(source: viewController!, destination: destinationVC)
	//  }
	//}
	// MARK: Navigation
	//func navigateToSomewhere(source: IntroGPSSetUpViewController, destination: SomewhereViewController)
	//{
	//  source.show(destination, sender: nil)
	//}  
	// MARK: Passing data
	//func passDataToSomewhere(source: IntroGPSSetUpDataStore, destination: inout SomewhereDataStore)
	//{
	//  destination.name = source.name
	//}
}
