//
//  IntroGPSSetUpInteractor.swift
//  fuelhunter
//
//  Created by Guntis on 02/08/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol IntroGPSSetUpBusinessLogic {
  	func userAskedForGPSAccess()
}

class IntroGPSSetUpInteractor: IntroGPSSetUpBusinessLogic {

  	// MARK: IntroGPSSetUpBusinessLogic

  	func userAskedForGPSAccess() {
		AppSettingsWorker.shared.userPressedButtonToGetGPSAccess { result in
			ScenesManager.shared.advanceAppSceneState()
		}
  	}
}
