//
//  IntroGPSSetUpViewController.swift
//  fuelhunter
//
//  Created by Guntis on 02/08/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol IntroGPSSetUpDisplayLogic: class {
  	func displayData(viewModel: IntroGPSSetUp.Something.ViewModel)
}

class IntroGPSSetUpViewController: UIViewController, IntroGPSSetUpDisplayLogic, IntroGPSSetUpLayoutViewLogic {
  	var interactor: IntroGPSSetUpBusinessLogic?
  	var router: (NSObjectProtocol & IntroGPSSetUpRoutingLogic & IntroGPSSetUpDataPassing)?
	var layoutView: IntroGPSSetUpLayoutView!

  	// MARK: Object lifecycle

  	override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    	super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    	setup()
  	}

  	required init?(coder aDecoder: NSCoder) {
    	super.init(coder: aDecoder)
    	setup()
  	}

  	// MARK: View lifecycle

  	override func viewDidLoad() {
    	super.viewDidLoad()
    	self.view.backgroundColor = .white
    	setUpView()
    	loadData()
  	}

  	// MARK: Set up

	private func setup() {
		let viewController = self
		let interactor = IntroGPSSetUpInteractor()
		let presenter = IntroGPSSetUpPresenter()
		let router = IntroGPSSetUpRouter()
		viewController.interactor = interactor
		viewController.router = router
		interactor.presenter = presenter
		presenter.viewController = viewController
		router.viewController = viewController
		router.dataStore = interactor
  	}

	func setUpView() {
		layoutView = IntroGPSSetUpLayoutView.init(frame: CGRect.init(x: 0, y: 0, width: self.view.frame.width, height: 100))
		self.view.addSubview(layoutView)
		layoutView.topAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.topAnchor).isActive = true
        layoutView.leftAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.leftAnchor).isActive = true
        layoutView.rightAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.rightAnchor).isActive = true
        layoutView.bottomAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.bottomAnchor).isActive = true
		layoutView.controller = self
	}

	// MARK: Functions

  	func loadData() {
    	let request = IntroGPSSetUp.Something.Request()
    	interactor?.loadData(request: request)
  	}

  	func displayData(viewModel: IntroGPSSetUp.Something.ViewModel) {
    	//nameTextField.text = viewModel.name
  	}

  	// MARK: IntroNotifSetUpLayoutViewLogic

  	func giveAccessButtonPressed() {
		let request = IntroGPSSetUp.Something.Request()
		interactor?.userAskedForGPSAccess(request: request)
  	}

  	func laterButtonPressed() {
  		ScenesManager.shared.advanceAppSceneState()
  	}
}
