//
//  IntroGPSSetUpRouter.swift
//  fuelhunter
//
//  Created by Guntis on 02/08/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol IntroGPSSetUpRoutingLogic {
  	//func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol IntroGPSSetUpDataPassing {
  	var dataStore: IntroGPSSetUpDataStore? { get }
}

class IntroGPSSetUpRouter: NSObject, IntroGPSSetUpRoutingLogic, IntroGPSSetUpDataPassing {
  	weak var viewController: IntroGPSSetUpViewController?
  	var dataStore: IntroGPSSetUpDataStore?
}
