//
//  IntroGPSSetUpInteractor.swift
//  fuelhunter
//
//  Created by Guntis on 02/08/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol IntroGPSSetUpBusinessLogic {
  	func loadData(request: IntroGPSSetUp.Something.Request)
  	func userAskedForGPSAccess(request: IntroGPSSetUp.Something.Request)
}

protocol IntroGPSSetUpDataStore {
}

class IntroGPSSetUpInteractor: IntroGPSSetUpBusinessLogic, IntroGPSSetUpDataStore {
  	var presenter: IntroGPSSetUpPresentationLogic?
  	var worker: IntroGPSSetUpWorker?
  	var appSettingsWorker = AppSettingsWorker.shared

  	// MARK: IntroGPSSetUpBusinessLogic

  	func loadData(request: IntroGPSSetUp.Something.Request) {
    	worker = IntroGPSSetUpWorker()
    	worker?.doSomeWork()
    	let response = IntroGPSSetUp.Something.Response()
    	presenter?.presentData(response: response)
  	}

  	func userAskedForGPSAccess(request: IntroGPSSetUp.Something.Request) {
		appSettingsWorker.userPressedButtonToGetGPSAccess { result in 
			ScenesManager.shared.advanceAppSceneState()
		}
  	}
}
