//
//  IntroGPSSetUpViewController.swift
//  fuelhunter
//
//  Created by Guntis on 02/08/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class IntroGPSSetUpViewController: UIViewController, IntroGPSSetUpLayoutViewLogic {
  	var interactor: IntroGPSSetUpBusinessLogic?
	var layoutView: IntroGPSSetUpLayoutView!

  	// MARK: Object lifecycle

  	override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    	super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    	setup()
  	}

  	required init?(coder aDecoder: NSCoder) {
    	super.init(coder: aDecoder)
    	setup()
  	}

  	// MARK: View lifecycle

  	override func viewDidLoad() {
    	super.viewDidLoad()
    	self.view.backgroundColor = .white
    	setUpView()
  	}

  	// MARK: Set up

	private func setup() {
		let viewController = self
		let interactor = IntroGPSSetUpInteractor()
		viewController.interactor = interactor
  	}

	private func setUpView() {
		layoutView = IntroGPSSetUpLayoutView(frame: CGRect(x: 0, y: 0, width: self.view.frame.width, height: 100))
		self.view.addSubview(layoutView)
		layoutView.topAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.topAnchor).isActive = true
        layoutView.leftAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.leftAnchor).isActive = true
        layoutView.rightAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.rightAnchor).isActive = true
        layoutView.bottomAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.bottomAnchor).isActive = true
		layoutView.controller = self
	}

  	// MARK: IntroNotifSetUpLayoutViewLogic

  	func giveAccessButtonPressed() {
		interactor?.userAskedForGPSAccess()
  	}

  	func laterButtonPressed() {
  		ScenesManager.shared.advanceAppSceneState()
  	}
}
