//
//  IntroGPSSetUpPresenter.swift
//  fuelhunter
//
//  Created by Guntis on 02/08/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol IntroGPSSetUpPresentationLogic {
  	func presentSomething(response: IntroGPSSetUp.Something.Response)
}

class IntroGPSSetUpPresenter: IntroGPSSetUpPresentationLogic {
  	weak var viewController: IntroGPSSetUpDisplayLogic?

  	// MARK: Do something

  	func presentSomething(response: IntroGPSSetUp.Something.Response) {
    	let viewModel = IntroGPSSetUp.Something.ViewModel()
    	viewController?.displaySomething(viewModel: viewModel)
  	}
}
