//
//  MainFuelListRouter.swift
//  fuelhunter
//
//  Created by Guntis on 03/06/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainFuelListRoutingLogic {
	@objc func routeToSettings()
	func routeToAppAccuracyInfo()
	func routeToAppSavingsInfo()
}

protocol MainFuelListDataPassing {
	var dataStore: MainFuelListDataStore? { get }
}

class MainFuelListRouter: NSObject, MainFuelListRoutingLogic, MainFuelListDataPassing {
	weak var viewController: MainFuelListViewController?
	var dataStore: MainFuelListDataStore?

  	// MARK: Routing

	@objc func routeToSettings() {
  		navigateToSettings(source: viewController!, destination: SettingsViewController())
  	}
  	
  	func routeToAppAccuracyInfo() {
  		navigateToSettings(source: viewController!, destination: AppAccuracyInfoViewController())
  	}

	func routeToAppSavingsInfo() {
		let storyboard = UIStoryboard(name: "Main", bundle: nil)
  		let destinationVC = storyboard.instantiateViewController(withIdentifier: "appSavingsInfoViewController") as! AppSavingsInfoViewController
  		navigateToSettings(source: viewController!, destination: destinationVC)
	}
  	
  	// MARK: Navigation  
	func navigateToSettings(source: MainFuelListViewController, destination: UIViewController) {
		source.navigationItem.backBarButtonItem = UIBarButtonItem(title: "", style: .plain, target: nil, action: nil)
		source.navigationController?.navigationBar.topItem?.backBarButtonItem = UIBarButtonItem(title: "", style: .plain, target: nil, action: nil)
		source.show(destination, sender: nil)
  	}
}
