//
//  IntroChooseFuelTypeViewController.swift
//  fuelhunter
//
//  Created by Guntis on 25/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol IntroChooseFuelTypeDisplayLogic: class {
  	func displayListWithData(viewModel: IntroChooseFuelType.FuelCells.ViewModel)
}

class IntroChooseFuelTypeViewController: UIViewController, IntroChooseFuelTypeDisplayLogic, IntroChooseFuelTypeLayoutViewLogic, FuelTypeListCellSwitchLogic {
	
	
  	var interactor: IntroChooseFuelTypeBusinessLogic?
  	var router: (NSObjectProtocol & IntroChooseFuelTypeRoutingLogic & IntroChooseFuelTypeDataPassing)?
	var layoutView: IntroChooseFuelTypeLayoutView!
  	// MARK: Object lifecycle

  	override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    	super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    	setup()
  	}

  	required init?(coder aDecoder: NSCoder) {
    	super.init(coder: aDecoder)
    	setup()
  	}

  	// MARK: Setup

  	private func setup() {
		let viewController = self
		let interactor = IntroChooseFuelTypeInteractor()
		let presenter = IntroChooseFuelTypePresenter()
		let router = IntroChooseFuelTypeRouter()
		viewController.interactor = interactor
		viewController.router = router
		interactor.presenter = presenter
		presenter.viewController = viewController
		router.viewController = viewController
		router.dataStore = interactor
  	}

  	// MARK: View lifecycle

  	override func viewDidLoad() {
    	super.viewDidLoad()
    	self.view.backgroundColor = .white
		setUpView()
    	getData()
  	}
	
	func setUpView() {
		layoutView = IntroChooseFuelTypeLayoutView.init(frame: CGRect.init(x: 0, y: 0, width: self.view.frame.width, height: 100))
		self.view.addSubview(layoutView)
		layoutView.topAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.topAnchor).isActive = true
        layoutView.leftAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.leftAnchor).isActive = true
        layoutView.rightAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.rightAnchor).isActive = true
        layoutView.bottomAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.bottomAnchor).isActive = true
		layoutView.controller = self
	}
	
  	// MARK: Do something

  	func getData() {
    	let request = IntroChooseFuelType.FuelCells.Request()
    	interactor?.getFuelTypesListData(request: request)
  	}

  	func displayListWithData(viewModel: IntroChooseFuelType.FuelCells.ViewModel) {
    	if (layoutView?.data.count)! == 0 {
			layoutView?.data = viewModel.displayedFuelCellItems
			layoutView?.tableView.reloadData()
		} else {
			layoutView?.data = viewModel.displayedFuelCellItems
		}
		
		layoutView?.nextButton.isEnabled = viewModel.nextButtonIsEnabled
  	}
  	
  	// MARK: IntroChooseFuelTypeLayoutViewLogic
  	func nextButtonWasPressed() {
  		ScenesManager.shared.advanceAppSceneState()
  	}
  	
  	// MARK: FuelTypeListCellSwitchLogic
  	func switchWasPressedOnTableViewCell(cell: FuelTypeListCell, withState state: Bool) {
		let indexPath = layoutView.tableView.indexPath(for: cell)
		let aData = layoutView.data[indexPath!.row] as IntroChooseFuelType.FuelCells.ViewModel.DisplayedFuelCellItem
		
		let request = IntroChooseFuelType.SwitchToggled.Request.init(fuelType: aData.fuelType, state: state)
		interactor?.userToggledFuelType(request: request)
	}
}
