//
//  CompaniesChooseListViewController.swift
//  fuelhunter
//
//  Created by Guntis on 04/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CompaniesChooseListDisplayLogic: class {
  	func displayListWithData(viewModel: CompaniesChooseList.CompanyCells.ViewModel)
}

class CompaniesChooseListViewController: UIViewController, CompaniesChooseListDisplayLogic, CompaniesChooseListLayoutViewLogic {
  	var interactor: CompaniesChooseListBusinessLogic?
  	var router: (NSObjectProtocol & CompaniesChooseListRoutingLogic & CompaniesChooseListDataPassing)?
	var layoutView: CompaniesChooseListLayoutView!

	// MARK: Object lifecycle

  	override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    	super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    	setup()
  	}

  	required init?(coder aDecoder: NSCoder) {
    	super.init(coder: aDecoder)
    	setup()
  	}

  	// MARK: View lifecycle

  	override func viewDidLoad() {
    	super.viewDidLoad()
		self.title = "settings_fuel_company_title".localized()
    	self.view.backgroundColor = .white
		setUpView()
    	getCompaniesListData()
  	}

	// MARK: Set up

	private func setup() {
		let viewController = self
		let interactor = CompaniesChooseListInteractor()
		let presenter = CompaniesChooseListPresenter()
		let router = CompaniesChooseListRouter()
		viewController.interactor = interactor
		viewController.router = router
		interactor.presenter = presenter
		presenter.viewController = viewController
		router.viewController = viewController
		router.dataStore = interactor
  	}

	func setUpView() {
		layoutView = CompaniesChooseListLayoutView(frame: CGRect(x: 0, y: 0, width: self.view.frame.width, height: 100))
		self.view.addSubview(layoutView)
		layoutView.topAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.topAnchor).isActive = true
        layoutView.leftAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.leftAnchor).isActive = true
        layoutView.rightAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.rightAnchor).isActive = true
        layoutView.bottomAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.bottomAnchor).isActive = true
		layoutView.controller = self
	}
	
  	// MARK: Functions

  	func getCompaniesListData() {
    	let request = CompaniesChooseList.CompanyCells.Request()
    	interactor?.getCompaniesListData(request: request)
  	}

  	func displayListWithData(viewModel: CompaniesChooseList.CompanyCells.ViewModel) {
    	layoutView.updateData(data: viewModel.displayedCompanyCellItems)
  	}

  	// MARK: CompaniesChooseListLayoutViewLogic

  	func switchWasPressedFor(companyName: String, withState state: Bool) {
		let request = CompaniesChooseList.SwitchToggled.Request(companyName: companyName, state: state)
		interactor?.userToggledCompanyType(request: request)
	}
}
