//
//  CompaniesChooseListPresenter.swift
//  fuelhunter
//
//  Created by Guntis on 04/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CompaniesChooseListPresentationLogic {
  	func presentSomething(response: CompaniesChooseList.CompanyCells.Response)
}

class CompaniesChooseListPresenter: CompaniesChooseListPresentationLogic {
  	weak var viewController: CompaniesChooseListDisplayLogic?
  	
  	// MARK: CompaniesChooseListPresentationLogic

  	func presentSomething(response:  CompaniesChooseList.CompanyCells.Response) {

		let array =  [
			CompaniesChooseList.CompanyCells.ViewModel.DisplayedCompanyCellItem.init(companyType: .typeCheapest, title: "Lētākā", description: "Ieslēdzot šo - vienmēr tiks rādīta arī tā kompānija, kurai Latvijā ir lētākā degviela attiecīgajā brīdī", imageName: "", toggleStatus: response.companyCheapestStatus),
			CompaniesChooseList.CompanyCells.ViewModel.DisplayedCompanyCellItem.init(companyType: .typeNeste, title: "Neste", description: "Lētākā Degviela Rīgā.", imageName: "neste_tiny_logo", toggleStatus: response.companyNesteStatus),
			CompaniesChooseList.CompanyCells.ViewModel.DisplayedCompanyCellItem.init(companyType: .typeCircleK, title: "Circle K", description: "Lētākā Degviela Rīgā.", imageName: "circle_k_tiny_logo", toggleStatus: response.companyCircleKStatus),
			CompaniesChooseList.CompanyCells.ViewModel.DisplayedCompanyCellItem.init(companyType: .typeKool, title: "Kool", description: "Zemākās cenas DUS tīklā Latvijā.", imageName: "kool_tiny_logo", toggleStatus: response.companyKoolStatus),
			CompaniesChooseList.CompanyCells.ViewModel.DisplayedCompanyCellItem.init(companyType: .typeLN, title: "Latvijas Nafta", description: "Zemākās cenas DUS tīklā Latvijā, pa reģioniem (Rīgas rajons, Liepājas rajons, Ventspils rajons, Zemgale, Vidzeme, Latgale).", imageName: "ln_tiny_logo", toggleStatus: response.companyLatvijasNaftaStatus),
			CompaniesChooseList.CompanyCells.ViewModel.DisplayedCompanyCellItem.init(companyType: .typeVirsi, title: "Virši", description: "Lētākā degviela Rīgā un Pierīgā.", imageName: "virshi_tiny_logo", toggleStatus: response.companyVirsiStatus),
			CompaniesChooseList.CompanyCells.ViewModel.DisplayedCompanyCellItem.init(companyType: .typeGotikaAuto, title: "Gotika Auto", description: "Zemākās cenas DUS tīklā Latvijā.", imageName: "gotika_tiny_logo", toggleStatus: response.companyGotikaStatus)
			]

    	let viewModel = CompaniesChooseList.CompanyCells.ViewModel.init(displayedCompanyCellItems: array)
    	viewController?.displayListWithData(viewModel: viewModel)
  	}
}
