//
//  FuelListInteractor.swift
//  fuelhunter
//
//  Created by Guntis on 03/06/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FuelListBusinessLogic {
	func fetchPrices(request: FuelList.FetchPrices.Request)
}

protocol FuelListDataStore {
	//var name: String { get set }
}

class FuelListInteractor: FuelListBusinessLogic, FuelListDataStore {
	
	var presenter: FuelListPresentationLogic?
	var worker: FuelListWorker?
	//var name: String = ""

	var pricesWorker = PriceWorker(priceStore: PricesMemoryStore())
  	var prices: [Price]?
  
	// MARK: Do something

	func fetchPrices(request: FuelList.FetchPrices.Request) {
//		worker = FuelListWorker()
//		worker?.doSomeWork()

		pricesWorker.fetchPrices { (fetchedPrices) -> Void in
			self.prices = fetchedPrices
			let response = FuelList.FetchPrices.Response(prices: fetchedPrices)
			self.presenter?.presentSomething(response: response)
		}
	}
}
