//
//  FuelListModels.swift
//  fuelhunter
//
//  Created by Guntis on 03/06/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum FuelList {
	// MARK: Use cases

	enum RevealMap {
		struct Request {
			var selectedCompany: Company
			var selectedFuelType: FuelType
			var selectedCellYPosition: CGFloat
		}
		struct Response {
			var prices: [Price]
			var selectedCompany: Company
			var selectedFuelType: FuelType
			var selectedCellYPosition: CGFloat
		}
		struct ViewModel {
			var slectedFuelTypePrices: [Price]
			var selectedCompany: Company
			var selectedFuelType: FuelType
			var selectedCellYPosition: CGFloat
		}
	}
	enum FetchPrices {
		struct Request {
		}
		struct Response {
			var prices: [Price]
		}
		struct ViewModel {
			struct DisplayedPrice: Equatable {
				var id: String
				var company: Company
				var price: String
				var isPriceCheapest: Bool
				var fuelType: FuelType
				var addressDescription: String
				var address: [Address]
				var city: String
			}
			var displayedPrices: [[DisplayedPrice]]
		}
	}
	enum FindAPrice {
		struct Request {
			var selectedPrice: Price
		}
	}
}
