//
//  LoadedCityExplainInteractor.swift
//  fuelhunter
//
//  Created by Guntis on 10/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoadedCityExplainBusinessLogic {
	func getDataToShow(request: LoadedCity.Data.Request)
    func doneButtonPressed()
}

class LoadedCityExplainViewInteractor: LoadedCityExplainBusinessLogic {
  	var presenter: LoadedCityExplainPresentationLogic?

	// MARK: LoadedCityExplainBusinessLogic

  	func getDataToShow(request: LoadedCity.Data.Request) {
  		let cityName = AppSettingsWorker.shared.getStoredLastGPSDetectedCityName()
		let response = LoadedCity.Data.Response(cityName: cityName)
		presenter?.presentData(response: response)
  	}

  	func doneButtonPressed() {
  		presenter?.returnBackToPreviousViewController()
  	}
}
