//
//  LoadedCityExplainViewController.swift
//  fuelhunter
//
//  Created by Guntis on 10/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoadedCityExplainDisplayLogic: class {
  	func updateData(viewModel: LoadedCity.Data.ViewModel)
}

class LoadedCityExplainViewController: UIViewController, LoadedCityExplainLayoutViewLogic, LoadedCityExplainDisplayLogic {
  	var interactor: LoadedCityExplainBusinessLogic?
  	var router: (NSObjectProtocol & LoadedCityExplainViewRoutingLogic)?
	var layoutView: LoadedCityExplainLayoutView!

  	// MARK: Object lifecycle

  	override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    	super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    	setup()
  	}

  	required init?(coder aDecoder: NSCoder) {
    	super.init(coder: aDecoder)
    	setup()
  	}

  	// MARK: View lifecycle

  	override func viewDidLoad() {
    	super.viewDidLoad()
    	self.view.backgroundColor = .clear
    	setUpViews()
		getData()
  	}

  	override func viewDidAppear(_ animated: Bool) {
		super.viewDidAppear(animated)
	}

	override func viewDidDisappear(_ animated: Bool) {
		super.viewDidDisappear(animated)
		let notificationCenter = NotificationCenter.default
		notificationCenter.removeObserver(self)
	}

	override func viewWillAppear(_ animated: Bool) {
		super.viewWillAppear(animated)
		layoutView.animateBackgroundImageColorToState(visible: true)
	}

	override func viewWillDisappear(_ animated: Bool) {
		super.viewWillDisappear(animated)
		layoutView.animateBackgroundImageColorToState(visible: false)
	}

	// MARK: Set up

  	private func setup() {
		let viewController = self
		let interactor = LoadedCityExplainViewInteractor()
		let presenter = LoadedCityExplainPresenter()
		let router = LoadedCityExplainRouter()
		viewController.interactor = interactor
		viewController.router = router
		interactor.presenter = presenter
		presenter.viewController = viewController
		presenter.router = router
		router.viewController = viewController
  	}

  	private func setUpViews() {
		layoutView = LoadedCityExplainLayoutView(frame: CGRect(x: 0, y: 0, width: self.view.frame.width, height: 100))
		self.view.addSubview(layoutView)
		layoutView.topAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.topAnchor).isActive = true
        layoutView.leftAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.leftAnchor).isActive = true
        layoutView.rightAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.rightAnchor).isActive = true
        layoutView.bottomAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.bottomAnchor).isActive = true
		layoutView.controller = self
	}

	// MARK: Functions

	private func getData() {
		interactor?.getDataToShow(request: LoadedCity.Data.Request())
	}

	// MARK: LoadedCityExplainDisplayLogic

	func updateData(viewModel: LoadedCity.Data.ViewModel) {
		layoutView.updateData(data: viewModel)
	}

	// MARK: LoadedCityExplainLayoutViewLogic

	func doneButtonPressed() {
  		interactor?.doneButtonPressed()
  	}
}
