//
//  LoadedCityExplainModels.swift
//  fuelhunter
//
//  Created by Guntis on 10/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum LoadedCity {
  	// MARK: Use cases
	enum Data {
		struct Request {
		}
		struct Response {
			var cityName: String
		}
		struct ViewModel {
			var cityName: String
		}
  	}
}
