//
//  AreaEditPageRouter.swift
//  fuelhunter
//
//  Created by Guntis on 27/06/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MessageUI
import CoreData
import FirebaseCrashlytics
import CoreLocation

protocol AreaEditPageRoutingLogic {
	func popViewController()
}

protocol AreaEditPageDataPassing {
  	var dataStore: AreaEditPageDataStore? { get set }
}

class AreaEditPageRouter: NSObject, AreaEditPageRoutingLogic, AreaEditPageDataPassing {
  	weak var viewController: AreaEditPageViewController?
  	var dataStore: AreaEditPageDataStore?

	// MARK: AreaEditPageRoutingLogic

	func popViewController() {
		viewController?.navigationController?.popViewController(animated: true)
	}

	// MARK: Functions

	private func navigateToScene(source: UIViewController, destination: UIViewController) {
		source.navigationItem.backBarButtonItem = UIBarButtonItem(title: "", style: .plain, target: nil, action: nil)
		source.show(destination, sender: nil)
  	}
}
