//
//  AreaEditPageModels.swift
//  fuelhunter
//
//  Created by Guntis on 27/06/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Area {

  	// MARK: Use cases

	enum AreaEditPage {
		struct Request {
		}
		struct Response {
			var fetchedArea: AreasEntity
		}
		struct ViewModel {
			struct DisplayedCell: Equatable {
				var name: String
				var toggleOrCheckmarkIsOn: Bool
				var iconName: String
				var description: String
				var accessoryType: CellAccessoryType
				var functionalityType: CellFunctionalityType
			}
			var displayedCells: [[DisplayedCell]]
			var areaName: String
		}
  	}

  	enum ChangeName {
		struct Request {
			var newName: String
		}
  	}

  	enum ToggleCheapest {
		struct Request {
			var cheapest: Bool
		}
  	}

  	enum ToggleNotif {
		struct Request {
			var notif: Bool
		}
  	}
}
