//
//  AppSavingsInfoViewController.swift
//  fuelhunter
//
//  Created by Guntis on 15/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AppSavingsInfoDisplayLogic: class {
  	func displaySomething(viewModel: AppSavingsInfo.Something.ViewModel)
}

class AppSavingsInfoViewController: UIViewController, AppSavingsInfoDisplayLogic {
  	var interactor: AppSavingsInfoBusinessLogic?
  	var router: (NSObjectProtocol & AppSavingsInfoRoutingLogic & AppSavingsInfoDataPassing)?
	var layoutView: AppSavingsInfoLayoutView!

	// MARK: Object lifecycle

  	override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    	super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    	setup()
  	}

  	required init?(coder aDecoder: NSCoder) {
    	super.init(coder: aDecoder)
    	setup()
  	}

  	// MARK: View lifecycle

  	override func viewDidLoad() {
    	super.viewDidLoad()
    	self.title = "fuel_savings_title".localized()
    	self.view.backgroundColor = .white
    	setUpView()
  	}

	// Set up

	private func setup() {
		let viewController = self
		let interactor = AppSavingsInfoInteractor()
		let presenter = AppSavingsInfoPresenter()
		let router = AppSavingsInfoRouter()
		viewController.interactor = interactor
		viewController.router = router
		interactor.presenter = presenter
		presenter.viewController = viewController
		router.viewController = viewController
		router.dataStore = interactor
  	}

  	func setUpView() {
		layoutView = AppSavingsInfoLayoutView.init(frame: CGRect.init(x: 0, y: 0, width: self.view.frame.width, height: 100))
		self.view.addSubview(layoutView)
		layoutView.topAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.topAnchor).isActive = true
        layoutView.leftAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.leftAnchor).isActive = true
        layoutView.rightAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.rightAnchor).isActive = true
        layoutView.bottomAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.bottomAnchor).isActive = true
	}

  	// MARK: Functions

  	func displaySomething(viewModel: AppSavingsInfo.Something.ViewModel) {
  	}
}
