//
//  AppSavingsInfoRouter.swift
//  fuelhunter
//
//  Created by Guntis on 15/07/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AppSavingsInfoRoutingLogic {
  	//func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol AppSavingsInfoDataPassing {
  	var dataStore: AppSavingsInfoDataStore? { get }
}

class AppSavingsInfoRouter: NSObject, AppSavingsInfoRoutingLogic, AppSavingsInfoDataPassing {
  	weak var viewController: AppSavingsInfoViewController?
  	var dataStore: AppSavingsInfoDataStore?
}
