//
//  MapModels.swift
//  fuelhunter
//
//  Created by Guntis on 12/08/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Map {
  	// MARK: Use cases

	enum MapWasPressed {
		struct Request {
			var mapPoint: MapPoint
		}
		struct Response {
			var mapPoint: MapPoint
			var priceData: FuelList.FetchPrices.ViewModel.DisplayedPrice
		}
		struct ViewModel {
			var mapPoint: MapPoint
			var priceData: FuelList.FetchPrices.ViewModel.DisplayedPrice
		}
	}

	enum MapData {
		struct Request {
		}
		struct Response {
			var displayedPoints: [MapData.ViewModel.DisplayedMapPoint]
			var mapPoints: [MapPoint]
			var selectedPriceData: FuelList.FetchPrices.ViewModel.DisplayedPrice
			var selectedMapPoint: MapPoint
		}
		struct ViewModel {
			struct DisplayedMapPoint: Equatable {
				var id: String   // this is the price ID
				var subId: String // this is the sub-ID -  which is id + address
				var companyName: String
				var companyBigLogoName: String
				var companyBigGrayLogoName: String
				var price: String
				var isPriceCheapest: Bool
				var latitude: Double
				var longitude: Double
				var addressName: String
				var distanceInKm: Double
			}
			var displayedPoints: [DisplayedMapPoint]
			var mapPoints: [MapPoint]
			var selectedPriceData: FuelList.FetchPrices.ViewModel.DisplayedPrice
			var selectedMapPoint: MapPoint
		}
  	}
}
