//
//  AppAccuracyInfoViewController.swift
//  fuelhunter
//
//  Created by Guntis on 15/07/2019.
//  Copyright (c) 2019 myEmerg. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


class AppAccuracyInfoViewController: AboutAppViewController {
  	
  	// MARK: View lifecycle

  	override func viewDidLoad() {
    	super.viewDidLoad()
    	self.title = "Degvielas cenu precizitāte"
    }	
    	
	override func setUpTableViewHeader() {
		let header = AppAccuracyInfoTableHeaderView.init(frame: CGRect.init(x: 0, y: 0, width: self.view.frame.width, height: 100))
		header.translatesAutoresizingMaskIntoConstraints = false
		self.tableView.tableHeaderView = header
		header.widthAnchor.constraint(equalTo: self.tableView.widthAnchor).isActive = true
		header.layoutIfNeeded()
		tableView.tableHeaderView = header
	}
}
