//
//  MainFuelListRouter.swift
//  fuelhunter
//
//  Created by Guntis on 03/06/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainFuelListRoutingLogic {
	//func routeToSomewhere(segue: UIStoryboardSegue?)
	@objc func routeToSettings(sender: UIBarButtonItem?)
}

protocol MainFuelListDataPassing {
	var dataStore: MainFuelListDataStore? { get }
}

class MainFuelListRouter: NSObject, MainFuelListRoutingLogic, MainFuelListDataPassing {
	weak var viewController: MainFuelListViewController?
	var dataStore: MainFuelListDataStore?

  // MARK: Routing

  @objc func routeToSettings(sender: UIBarButtonItem?)
  {
//    if let segue = segue {
//      let destinationVC = segue.destination as! SettingsViewController
//      var destinationDS = destinationVC.router!.dataStore!
////      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//    } else {
//      let storyboard = UIStoryboard(name: "Main", bundle: nil)
//      let destinationVC = storyboard.instantiateViewController(withIdentifier:
//   "SomewhereViewController") as! SomewhereViewController
//      var destinationDS = destinationVC.router!.dataStore!
//      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//      navigateToSomewhere(source: viewController!, destination: destinationVC)
//    }
  }
  // MARK: Navigation  
  //func navigateToSomewhere(source: MainFuelListViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  // MARK: Passing data
  //func passDataToSomewhere(source: MainFuelListDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
