//
//  MainFuelListRouter.swift
//  fuelhunter
//
//  Created by Guntis on 03/06/2019.
//  Copyright (c) 2019 . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainFuelListRoutingLogic {
	@objc func routeToSettings()
}

protocol MainFuelListDataPassing {
	var dataStore: MainFuelListDataStore? { get }
}

class MainFuelListRouter: NSObject, MainFuelListRoutingLogic, MainFuelListDataPassing {
	weak var viewController: MainFuelListViewController?
	var dataStore: MainFuelListDataStore?

  	// MARK: Routing

	@objc func routeToSettings()
  	{
  		let storyboard = UIStoryboard(name: "Main", bundle: nil)
  		let destinationVC = storyboard.instantiateViewController(withIdentifier: "settingsViewController") as! SettingsViewController
  		navigateToSettings(source: viewController!, destination: destinationVC)
  	}
  	
  	// MARK: Navigation  
	func navigateToSettings(source: MainFuelListViewController, destination: SettingsViewController)
  	{
		source.navigationItem.backBarButtonItem = UIBarButtonItem(title: "", style: .plain, target: nil, action: nil)
		source.show(destination, sender: nil)
  	}
}
