//
//  MainFuelListInteractor.swift
//  fuelhunter
//
//  Created by Guntis on 03/06/2019.
//  Copyright (c) 2019 myEmerg. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainFuelListBusinessLogic {
	func fetchPrices(request: MainFuelList.FetchPrices.Request)
}

protocol MainFuelListDataStore {
	//var name: String { get set }
}

class MainFuelListInteractor: MainFuelListBusinessLogic, MainFuelListDataStore {
	
	var presenter: MainFuelListPresentationLogic?
	var worker: MainFuelListWorker?
	//var name: String = ""

	var pricesWorker = PriceWorker(priceStore: PricesMemoryStore())
  	var prices: [Price]?
  
	// MARK: Do something

	func fetchPrices(request: MainFuelList.FetchPrices.Request) {
//		worker = MainFuelListWorker()
//		worker?.doSomeWork()

		pricesWorker.fetchPrices { (fetchedPrices) -> Void in
			self.prices = fetchedPrices
			let response = MainFuelList.FetchPrices.Response(prices: fetchedPrices)
			self.presenter?.presentSomething(response: response)
		}
	}
}
